package ws.roberts.android.readibites;

import android.content.Context;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class RBLocationLab {
    private static RBLocationLab sLocation;
    private List<RBLocation> mLocations;

    public static RBLocationLab get(Context context) {
        if (sLocation == null) {
            sLocation = new RBLocationLab(context);
        }
        return sLocation;
    }

    protected RBLocationLab(Context context) {

        populateList();

    }

    public RBLocationLab() {

    }

    public void populateList() {
        mLocations = new ArrayList<>();

        RBLocation pretOracle = new RBLocation();
        pretOracle.setTitle("Pret A Manger (Oracle)");
        pretOracle.setFoodType("Cafe Cuisine");
        pretOracle.setArea("The Oracle");
        pretOracle.setIsCafe(true);
        pretOracle.setVegStatus(1);
        pretOracle.setCalStatus(1);
        pretOracle.setGFStatus(1);
        pretOracle.generateSubtitle();
        pretOracle.generateTypeString();
        pretOracle.setMapSearch("https://www.google.com/maps/search/?api=1&query=pret+oracle+reading");
        pretOracle.setAllergenLink("https://odcdn2.zenedge.com/pretamanger-uk/allergen-guide/Allergen%20Guide%20130717.pdf");
        pretOracle.setPhoneNum("01189582942");
        mLocations.add(pretOracle);

        RBLocation bens = new RBLocation();
        bens.setTitle("Ben's Cookies");
        bens.setFoodType("Bakery");
        bens.setArea("The Oracle");
        bens.setIsDessertBar(true);
        bens.setVegStatus(3);
        bens.setCalStatus(1);
        bens.setGFStatus(3);
        bens.generateSubtitle();
        bens.generateTypeString();
        bens.setMapSearch("https://www.google.com/maps/search/?api=1&query=bens+cookies+reading");
        bens.setAllergenLink("https://www.benscookies.com/nutritional-information/");
        bens.setPhoneNum("01189507398");
        mLocations.add(bens);

        RBLocation boost = new RBLocation();
        boost.setTitle("Boost");
        boost.setFoodType("Smoothies & Juices");
        boost.setArea("The Oracle");
        boost.setIsJuiceBar(true);
        boost.setVegStatus(1);
        boost.setCalStatus(1);
        boost.setGFStatus(1);
        boost.generateSubtitle();
        boost.generateTypeString();
        boost.setMapSearch("https://www.google.com/maps/search/?api=1&query=boost+reading");
        boost.setAllergenLink("http://www.boostjuicebars.co.uk/wp-content/uploads/2016/08/2016-Updated-Hand-Menu.compressed.pdf");
        boost.setPhoneNum("01189599852");
        mLocations.add(boost);

        RBLocation bellaItalia = new RBLocation();
        bellaItalia.setTitle("Bella Italia");
        bellaItalia.setFoodType("Italian");
        bellaItalia.setArea("Oracle Riverside");
        bellaItalia.setIsRestaurant(true);
        bellaItalia.setVegStatus(1);
        bellaItalia.setCalStatus(2);
        bellaItalia.setGFStatus(1);
        bellaItalia.generateSubtitle();
        bellaItalia.generateTypeString();
        bellaItalia.setMapSearch("https://www.google.com/maps/search/?api=1&query=bella+italia+reading");
        bellaItalia.setAllergenLink("https://s3-eu-west-1.amazonaws.com/bella-italia-artifacts/bella-menu-allergens.pdf");
        bellaItalia.setPhoneNum("01189566963");
        mLocations.add(bellaItalia);

        RBLocation pizzaExpressRiv = new RBLocation();
        pizzaExpressRiv.setTitle("Pizza Express (Riverside)");
        pizzaExpressRiv.setFoodType("Italian");
        pizzaExpressRiv.setArea("Oracle Riverside");
        pizzaExpressRiv.setIsRestaurant(true);
        pizzaExpressRiv.setVegStatus(2);
        pizzaExpressRiv.setCalStatus(2);
        pizzaExpressRiv.setGFStatus(1);
        pizzaExpressRiv.generateSubtitle();
        pizzaExpressRiv.generateTypeString();
        pizzaExpressRiv.setMapSearch("https://www.google.com/maps/search/?api=1&query=pizza+express+oracle+reading");
        pizzaExpressRiv.setAllergenLink("https://www.pizzaexpress.com/~/media/files/pdfs/nutritionals/pex_allergens-our-food.ashx");
        pizzaExpressRiv.setPhoneNum("01189574411");
        mLocations.add(pizzaExpressRiv);

        RBLocation slugLettuce = new RBLocation();
        slugLettuce.setTitle("The Slug and Lettuce");
        slugLettuce.setFoodType("Gastropub Grub");
        slugLettuce.setArea("Oracle Riverside");
        slugLettuce.setIsGastroPub(true);
        slugLettuce.setVegStatus(2);
        slugLettuce.setCalStatus(3);
        slugLettuce.setGFStatus(2);
        slugLettuce.generateSubtitle();
        slugLettuce.generateTypeString();
        slugLettuce.setMapSearch("https://www.google.com/maps/search/?api=1&query=slug+and+lettuce+reading");
        slugLettuce.setPhoneNum("01189571839");
        mLocations.add(slugLettuce);

        RBLocation comptoir = new RBLocation();
        comptoir.setTitle("Comptoir Libanais");
        comptoir.setFoodType("Lebanese");
        comptoir.setArea("Oracle Riverside");
        comptoir.setIsRestaurant(true);
        comptoir.setVegStatus(1);
        comptoir.setCalStatus(3);
        comptoir.setGFStatus(1);
        comptoir.generateSubtitle();
        comptoir.generateTypeString();
        comptoir.setMapSearch("https://www.google.com/maps/search/?api=1&query=comptoir+libanais+reading");
        comptoir.setAllergenLink("https://www.comptoirlibanais.com/menu/reading-coming-soon/main/");
        comptoir.setPhoneNum("01183213999");
        mLocations.add(comptoir);

        RBLocation allBarOne = new RBLocation();
        allBarOne.setTitle("All Bar One");
        allBarOne.setFoodType("Gastropub Grub");
        allBarOne.setArea("Oracle Riverside");
        allBarOne.setIsBar(true);
        allBarOne.setVegStatus(1);
        allBarOne.setCalStatus(3);
        allBarOne.setGFStatus(2);
        allBarOne.generateSubtitle();
        allBarOne.generateTypeString();
        allBarOne.setMapSearch("https://www.google.com/maps/search/?api=1&query=all+bar+one+reading");
        allBarOne.setPhoneNum("01189596749");
        mLocations.add(allBarOne);

        RBLocation missionBurrito = new RBLocation();
        missionBurrito.setTitle("Mission Burrito");
        missionBurrito.setFoodType("Mexican");
        missionBurrito.setArea("Oracle Riverside");
        missionBurrito.setIsRestaurant(true);
        missionBurrito.setVegStatus(1);
        missionBurrito.setCalStatus(3);
        missionBurrito.setGFStatus(1);
        missionBurrito.generateSubtitle();
        missionBurrito.generateTypeString();
        missionBurrito.setMapSearch("https://www.google.com/maps/search/?api=1&query=mission+burrito+reading");
        missionBurrito.setPhoneNum("01189511999");
        mLocations.add(missionBurrito);

        RBLocation wagamama = new RBLocation();
        wagamama.setTitle("Wagamama");
        wagamama.setFoodType("Japanese");
        wagamama.setArea("Oracle Riverside");
        wagamama.setIsRestaurant(true);
        wagamama.setVegStatus(2);
        wagamama.setCalStatus(3);
        wagamama.setGFStatus(2);
        wagamama.generateSubtitle();
        wagamama.generateTypeString();
        wagamama.setMapSearch("https://www.google.com/maps/search/?api=1&query=wagamama+reading");
        wagamama.setPhoneNum("01189511599");
        mLocations.add(wagamama);

        RBLocation giraffe = new RBLocation();
        giraffe.setTitle("Giraffe");
        giraffe.setFoodType("International");
        giraffe.setArea("Oracle Riverside");
        giraffe.setIsRestaurant(true);
        giraffe.setVegStatus(1);
        giraffe.setCalStatus(3);
        giraffe.setGFStatus(1);
        giraffe.generateSubtitle();
        giraffe.generateTypeString();
        giraffe.setMapSearch("https://www.google.com/maps/search/?api=1&query=giraffe+reading");
        giraffe.setAllergenLink("https://www.giraffe.net/allergens/menu/reading");
        giraffe.setPhoneNum("01189590101");
        mLocations.add(giraffe);

        RBLocation lasIguanas = new RBLocation();
        lasIguanas.setTitle("Las Iguanas");
        lasIguanas.setFoodType("Latin American");
        lasIguanas.setArea("Oracle Riverside");
        lasIguanas.setIsRestaurant(true);
        lasIguanas.setVegStatus(1);
        lasIguanas.setCalStatus(3);
        lasIguanas.setGFStatus(1);
        lasIguanas.generateSubtitle();
        lasIguanas.generateTypeString();
        lasIguanas.setMapSearch("https://www.google.com/maps/search/?api=1&query=las+iguanas+reading");
        lasIguanas.setAllergenLink("https://s3.amazonaws.com/las-iguanas-artefacts/las-iguanas-allergen-information.pdf");
        lasIguanas.setPhoneNum("01189566200");
        mLocations.add(lasIguanas);

        RBLocation jamiesItalian = new RBLocation();
        jamiesItalian.setTitle("Jamie's Italian");
        jamiesItalian.setFoodType("Italian");
        jamiesItalian.setArea("Oracle Riverside");
        jamiesItalian.setIsRestaurant(true);
        jamiesItalian.setVegStatus(2);
        jamiesItalian.setCalStatus(3);
        jamiesItalian.setGFStatus(1);
        jamiesItalian.generateSubtitle();
        jamiesItalian.generateTypeString();
        jamiesItalian.setMapSearch("https://www.google.com/maps/search/?api=1&query=jamies+italian+reading");
        jamiesItalian.setPhoneNum("01189070808");
        mLocations.add(jamiesItalian);

        RBLocation pizzaHut = new RBLocation();
        pizzaHut.setTitle("Pizza Hut");
        pizzaHut.setFoodType("Italian");
        pizzaHut.setArea("Oracle Riverside");
        pizzaHut.setIsRestaurant(true);
        pizzaHut.setVegStatus(1);
        pizzaHut.setCalStatus(1);
        pizzaHut.setGFStatus(1);
        pizzaHut.generateSubtitle();
        pizzaHut.generateTypeString();
        pizzaHut.setMapSearch("https://www.google.com/maps/search/?api=1&query=pizza+hut+oracle+reading");
        pizzaHut.setAllergenLink("https://www.pizzahut.co.uk/restaurants/r/SysSiteAssets/food/menu/nutrition/30_05_2017_p7_remodel_nutritional_booklet-1.pdf/");
        pizzaHut.setPhoneNum("01189596644");
        mLocations.add(pizzaHut);

        RBLocation nandosRiv = new RBLocation();
        nandosRiv.setTitle("Nandos (Riverside)");
        nandosRiv.setFoodType("Portuguese");
        nandosRiv.setArea("Oracle Riverside");
        nandosRiv.setIsRestaurant(true);
        nandosRiv.setVegStatus(2);
        nandosRiv.setCalStatus(1);
        nandosRiv.setGFStatus(1);
        nandosRiv.generateSubtitle();
        nandosRiv.generateTypeString();
        nandosRiv.setMapSearch("https://www.google.com/maps/search/?api=1&query=nandos+oracle+reading");
        nandosRiv.setAllergenLink("https://www.nandos.co.uk/food/menu");
        nandosRiv.setPhoneNum("01189502199");
        mLocations.add(nandosRiv);

        RBLocation millerAndCarter = new RBLocation();
        millerAndCarter.setTitle("Miller & Carter");
        millerAndCarter.setFoodType("Steakhouse");
        millerAndCarter.setArea("Oracle Riverside");
        millerAndCarter.setIsRestaurant(true);
        millerAndCarter.setVegStatus(2);
        millerAndCarter.setCalStatus(3);
        millerAndCarter.setGFStatus(2);
        millerAndCarter.generateSubtitle();
        millerAndCarter.generateTypeString();
        millerAndCarter.setMapSearch("https://www.google.com/maps/search/?api=1&query=miller+and+carter+reading");
        millerAndCarter.setPhoneNum("01189509961");
        mLocations.add(millerAndCarter);

        RBLocation browns = new RBLocation();
        browns.setTitle("Browns");
        browns.setFoodType("British");
        browns.setArea("Oracle Riverside");
        browns.setIsRestaurant(true);
        browns.setVegStatus(1);
        browns.setCalStatus(3);
        browns.setGFStatus(1);
        browns.generateSubtitle();
        browns.generateTypeString();
        browns.setMapSearch("https://www.google.com/maps/search/?api=1&query=browns+reading");
        browns.setPhoneNum("01189503137");
        mLocations.add(browns);

        RBLocation handmadeBCo = new RBLocation();
        handmadeBCo.setTitle("Handmade Burger Co");
        handmadeBCo.setFoodType("American");
        handmadeBCo.setArea("Oracle Riverside");
        handmadeBCo.setIsRestaurant(true);
        handmadeBCo.setVegStatus(1);
        handmadeBCo.setCalStatus(3);
        handmadeBCo.setGFStatus(1);
        handmadeBCo.generateSubtitle();
        handmadeBCo.generateTypeString();
        handmadeBCo.setMapSearch("https://www.google.com/maps/search/?api=1&query=handmade+burger+co+reading");
        handmadeBCo.setAllergenLink("http://handmadeburger.co.uk/wp-content/uploads/2016/03/24284C-HBC-Allergy-Menu_WebMenu.pdf");
        handmadeBCo.setPhoneNum("01189588106");
        mLocations.add(handmadeBCo);

        RBLocation coteBras = new RBLocation();
        coteBras.setTitle("Cote Brasserie");
        coteBras.setFoodType("French");
        coteBras.setArea("Oracle Riverside");
        coteBras.setIsRestaurant(true);
        coteBras.setVegStatus(2);
        coteBras.setCalStatus(3);
        coteBras.setGFStatus(1);
        coteBras.generateSubtitle();
        coteBras.generateTypeString();
        coteBras.setMapSearch("https://www.google.com/maps/search/?api=1&query=cote+brasserie+reading");
        coteBras.setPhoneNum("01189591180");
        mLocations.add(coteBras);

        RBLocation tgisRiv = new RBLocation();
        tgisRiv.setTitle("TGI Fridays (Riverside)");
        tgisRiv.setFoodType("American");
        tgisRiv.setArea("Oracle Riverside");
        tgisRiv.setIsRestaurant(true);
        tgisRiv.setVegStatus(1);
        tgisRiv.setCalStatus(3);
        tgisRiv.setGFStatus(1);
        tgisRiv.generateSubtitle();
        tgisRiv.generateTypeString();
        tgisRiv.setMapSearch("https://www.google.com/maps/search/?api=1&query=tgi+fridays+oracle+centre+reading");
        tgisRiv.setAllergenLink("https://www.tgifridays.co.uk/reading/the-grill/#allergy-menu");
        tgisRiv.setPhoneNum("03442646052");
        mLocations.add(tgisRiv);


        RBLocation francoManca = new RBLocation();
        francoManca.setTitle("Franco Manca");
        francoManca.setFoodType("Italian");
        francoManca.setArea("Oracle Riverside");
        francoManca.setIsRestaurant(true);
        francoManca.setVegStatus(3);
        francoManca.setCalStatus(3);
        francoManca.setGFStatus(3);
        francoManca.generateSubtitle();
        francoManca.generateTypeString();
        francoManca.setMapSearch("https://www.google.com/maps/search/?api=1&query=franco+manca+reading");
        francoManca.setPhoneNum("01189952086");
        mLocations.add(francoManca);

        RBLocation auntieAnnes = new RBLocation();
        auntieAnnes.setTitle("Auntie Annes");
        auntieAnnes.setFoodType("Bakery");
        auntieAnnes.setArea("The Oracle");
        auntieAnnes.setIsDessertBar(true);
        auntieAnnes.setVegStatus(3);
        auntieAnnes.setCalStatus(1);
        auntieAnnes.setGFStatus(2);
        auntieAnnes.generateSubtitle();
        auntieAnnes.generateTypeString();
        auntieAnnes.setMapSearch("https://www.google.com/maps/search/?api=1&query=auntie+annes+reading");
        auntieAnnes.setAllergenLink("http://www.auntieannes.com/public/pdf/allergen-information.pdf");
        auntieAnnes.setPhoneNum("01189504853");
        mLocations.add(auntieAnnes);

        RBLocation fiveGuys = new RBLocation();
        fiveGuys.setTitle("Five Guys");
        fiveGuys.setFoodType("American");
        fiveGuys.setArea("The Oracle");
        fiveGuys.setIsRestaurant(true);
        fiveGuys.setVegStatus(2);
        fiveGuys.setCalStatus(1);
        fiveGuys.setGFStatus(2);
        fiveGuys.generateSubtitle();
        fiveGuys.generateTypeString();
        fiveGuys.setMapSearch("https://www.google.com/maps/search/?api=1&query=five+guys+reading");
        fiveGuys.setAllergenLink("https://www.fiveguys.co.uk/download/allergens.pdf");
        fiveGuys.setPhoneNum("01189573931");
        mLocations.add(fiveGuys);

        RBLocation yoSushi = new RBLocation();
        yoSushi.setTitle("YO! Sushi");
        yoSushi.setFoodType("Japanese");
        yoSushi.setArea("The Oracle");
        yoSushi.setIsRestaurant(true);
        yoSushi.setVegStatus(1);
        yoSushi.setCalStatus(1);
        yoSushi.setGFStatus(1);
        yoSushi.generateSubtitle();
        yoSushi.generateTypeString();
        yoSushi.setMapSearch("https://www.google.com/maps/search/?api=1&query=yo+sushi+reading");
        yoSushi.setAllergenLink("http://yosushi.mysaffronportal.com/Menus");
        yoSushi.setPhoneNum("01189144630");
        mLocations.add(yoSushi);

        RBLocation cau = new RBLocation();
        cau.setTitle("Cau");
        cau.setFoodType("Argentinian");
        cau.setArea("The Oracle");
        cau.setIsRestaurant(true);
        cau.setVegStatus(3);
        cau.setCalStatus(3);
        cau.setGFStatus(2);
        cau.generateSubtitle();
        cau.generateTypeString();
        cau.setMapSearch("https://www.google.com/maps/search/?api=1&query=cau+reading");
        cau.setAllergenLink("https://www.caurestaurants.com/uploads/1-CAU_SummerALC-2017.pdf");
        cau.setPhoneNum("01189505559");
        mLocations.add(cau);

        RBLocation fuel = new RBLocation();
        fuel.setTitle("Fuel");
        fuel.setFoodType("Smoothies & Juices");
        fuel.setArea("The Oracle");
        fuel.setIsJuiceBar(true);
        fuel.setVegStatus(1);
        fuel.setCalStatus(1);
        fuel.setGFStatus(1);
        fuel.generateSubtitle();
        fuel.generateTypeString();
        fuel.setMapSearch("https://www.google.com/maps/search/?api=1&query=fuel+juice+bar+reading");
        fuel.setAllergenLink("http://fueljuicebars.com/nutritional-info.pdf");
        fuel.setPhoneNum("01189597904");
        mLocations.add(fuel);

        RBLocation lonStrBras = new RBLocation();
        lonStrBras.setTitle("London Street Brasserie");
        lonStrBras.setFoodType("European");
        lonStrBras.setArea("Town Center");
        lonStrBras.setIsRestaurant(true);
        lonStrBras.setVegStatus(1);
        lonStrBras.setCalStatus(3);
        lonStrBras.setGFStatus(1);
        lonStrBras.generateSubtitle();
        lonStrBras.generateTypeString();
        lonStrBras.setMapSearch("https://www.google.com/maps/search/?api=1&query=london+street+brasserie+reading");
        lonStrBras.setPhoneNum("01189505036");
        mLocations.add(lonStrBras);

        RBLocation caffeineAndCocktails = new RBLocation();
        caffeineAndCocktails.setTitle("Caffeine & Cocktails");
        caffeineAndCocktails.setFoodType("Upscale Gastro");
        caffeineAndCocktails.setArea("Town Center");
        caffeineAndCocktails.setIsBar(true);
        caffeineAndCocktails.setVegStatus(2);
        caffeineAndCocktails.setCalStatus(3);
        caffeineAndCocktails.setGFStatus(2);
        caffeineAndCocktails.generateSubtitle();
        caffeineAndCocktails.generateTypeString();
        caffeineAndCocktails.setMapSearch("https://www.google.com/maps/search/?api=1&query=caffeine+cocktails+reading");
        caffeineAndCocktails.setPhoneNum("01189571365");
        mLocations.add(caffeineAndCocktails);

        RBLocation wrapItUp = new RBLocation();
        wrapItUp.setTitle("Wrap It Up!");
        wrapItUp.setFoodType("Mexican");
        wrapItUp.setArea("Town Center");
        wrapItUp.setIsRestaurant(true);
        wrapItUp.setVegStatus(2);
        wrapItUp.setCalStatus(3);
        wrapItUp.setGFStatus(2);
        wrapItUp.generateSubtitle();
        wrapItUp.generateTypeString();
        wrapItUp.setMapSearch("https://www.google.com/maps/search/?api=1&query=wrap+it+up+reading");
        wrapItUp.setPhoneNum("01189585623");
        mLocations.add(wrapItUp);

        RBLocation royalTandoori = new RBLocation();
        royalTandoori.setTitle("Royal Tandoori");
        royalTandoori.setFoodType("Indian/Nepalese");
        royalTandoori.setArea("Town Center");
        royalTandoori.setIsRestaurant(true);
        royalTandoori.setVegStatus(2);
        royalTandoori.setCalStatus(3);
        royalTandoori.setGFStatus(3);
        royalTandoori.generateSubtitle();
        royalTandoori.generateTypeString();
        royalTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=royal+tandoori+reading");
        royalTandoori.setPhoneNum("01189572717");
        mLocations.add(royalTandoori);

        RBLocation dolceVita = new RBLocation();
        dolceVita.setTitle("Dolce Vita");
        dolceVita.setFoodType("Italian");
        dolceVita.setArea("Town Center");
        dolceVita.setIsRestaurant(true);
        dolceVita.setVegStatus(3);
        dolceVita.setCalStatus(3);
        dolceVita.setGFStatus(3);
        dolceVita.generateSubtitle();
        dolceVita.generateTypeString();
        dolceVita.setMapSearch("https://www.google.com/maps/search/?api=1&query=dolce+vita+reading");
        dolceVita.setPhoneNum("01189510530");
        mLocations.add(dolceVita);

        RBLocation theSoju = new RBLocation();
        theSoju.setTitle("The SOJU");
        theSoju.setFoodType("Korean BBQ");
        theSoju.setArea("Town Center");
        theSoju.setIsRestaurant(true);
        theSoju.setVegStatus(3);
        theSoju.setCalStatus(3);
        theSoju.setGFStatus(3);
        theSoju.generateSubtitle();
        theSoju.generateTypeString();
        theSoju.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+soju+reading");
        theSoju.setPhoneNum("01183346182");
        mLocations.add(theSoju);

        RBLocation bolan = new RBLocation();
        bolan.setTitle("Bolan");
        bolan.setFoodType("Thai");
        bolan.setArea("Town Center");
        bolan.setIsRestaurant(true);
        bolan.setVegStatus(2);
        bolan.setCalStatus(3);
        bolan.setGFStatus(1);
        bolan.generateSubtitle();
        bolan.generateTypeString();
        bolan.setMapSearch("https://www.google.com/maps/search/?api=1&query=bolan+reading");
        bolan.setAllergenLink("http://www.bolanthaicuisine.co.uk/wp-content/uploads/2016/08/Lunch.pdf");
        bolan.setPhoneNum("01189568881");
        mLocations.add(bolan);

        RBLocation prezzo = new RBLocation();
        prezzo.setTitle("Prezzo");
        prezzo.setFoodType("Italian");
        prezzo.setArea("Town Center");
        prezzo.setIsRestaurant(true);
        prezzo.setVegStatus(2);
        prezzo.setCalStatus(3);
        prezzo.setGFStatus(1);
        prezzo.generateSubtitle();
        prezzo.generateTypeString();
        prezzo.setMapSearch("https://www.google.com/maps/search/?api=1&query=prezzo+reading");
        prezzo.setAllergenLink("https://www.prezzorestaurants.co.uk/globalassets/pdfs/september-2017/prezzo-main-18-09.pdf");
        prezzo.setPhoneNum("01189596092");
        mLocations.add(prezzo);

        RBLocation zeroDeg = new RBLocation();
        zeroDeg.setTitle("Zero Degrees");
        zeroDeg.setFoodType("European");
        zeroDeg.setArea("Town Center");
        zeroDeg.setIsBar(true);
        zeroDeg.setVegStatus(3);
        zeroDeg.setCalStatus(3);
        zeroDeg.setGFStatus(2);
        zeroDeg.generateSubtitle();
        zeroDeg.generateTypeString();
        zeroDeg.setMapSearch("https://www.google.com/maps/search/?api=1&query=zero+degrees+reading");
        zeroDeg.setPhoneNum("01189597959");
        mLocations.add(zeroDeg);

        RBLocation bluegrass = new RBLocation();
        bluegrass.setTitle("Bluegrass BBQ");
        bluegrass.setFoodType("BBQ");
        bluegrass.setArea("Town Center");
        bluegrass.setIsRestaurant(true);
        bluegrass.setVegStatus(2);
        bluegrass.setCalStatus(3);
        bluegrass.setGFStatus(1);
        bluegrass.generateSubtitle();
        bluegrass.generateTypeString();
        bluegrass.setMapSearch("https://www.google.com/maps/search/?api=1&query=bluegrass+bbq+reading");
        bluegrass.setPhoneNum("01189599112");
        mLocations.add(bluegrass);

        RBLocation lochFyne = new RBLocation();
        lochFyne.setTitle("Loch Fyne");
        lochFyne.setFoodType("Seafood");
        lochFyne.setArea("Town Center");
        lochFyne.setIsRestaurant(true);
        lochFyne.setVegStatus(1);
        lochFyne.setCalStatus(3);
        lochFyne.setGFStatus(1);
        lochFyne.generateSubtitle();
        lochFyne.generateTypeString();
        lochFyne.setMapSearch("https://www.google.com/maps/search/?api=1&query=loch+fyne+reading");
        lochFyne.setAllergenLink("https://www.lochfyneseafoodandgrill.co.uk/allergens");
        lochFyne.setPhoneNum("01189185850");
        mLocations.add(lochFyne);

        RBLocation threeGuineas = new RBLocation();
        threeGuineas.setTitle("The Three Guineas");
        threeGuineas.setFoodType("Gastropub Grub");
        threeGuineas.setArea("Town Center");
        threeGuineas.setIsGastroPub(true);
        threeGuineas.setVegStatus(2);
        threeGuineas.setCalStatus(3);
        threeGuineas.setGFStatus(2);
        threeGuineas.generateSubtitle();
        threeGuineas.generateTypeString();
        threeGuineas.setMapSearch("https://www.google.com/maps/search/?api=1&query=three+guineas+reading");
        threeGuineas.setPhoneNum("01189572743");
        mLocations.add(threeGuineas);

        RBLocation theGateway = new RBLocation();
        theGateway.setTitle("The Gateway");
        theGateway.setFoodType("Gastropub Grub");
        theGateway.setArea("Town Center");
        theGateway.setIsGastroPub(true);
        theGateway.setVegStatus(3);
        theGateway.setCalStatus(3);
        theGateway.setGFStatus(3);
        theGateway.generateSubtitle();
        theGateway.generateTypeString();
        theGateway.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+gateway+reading");
        theGateway.setPhoneNum("01189590376");
        mLocations.add(theGateway);

        RBLocation cosmo = new RBLocation();
        cosmo.setTitle("Cosmo");
        cosmo.setFoodType("International");
        cosmo.setArea("Town Center");
        cosmo.setIsRestaurant(true);
        cosmo.setVegStatus(2);
        cosmo.setCalStatus(3);
        cosmo.setGFStatus(2);
        cosmo.generateSubtitle();
        cosmo.generateTypeString();
        cosmo.setMapSearch("https://www.google.com/maps/search/?api=1&query=cosmo+reading");
        cosmo.setPhoneNum("01189595588");
        mLocations.add(cosmo);

        RBLocation nandosFri = new RBLocation();
        nandosFri.setTitle("Nandos (Friar St)");
        nandosFri.setFoodType("Portuguese");
        nandosFri.setArea("Town Center");
        nandosFri.setIsRestaurant(true);
        nandosFri.setVegStatus(2);
        nandosFri.setCalStatus(1);
        nandosFri.setGFStatus(1);
        nandosFri.generateSubtitle();
        nandosFri.generateTypeString();
        nandosFri.setMapSearch("https://www.google.com/maps/search/?api=1&query=nandos+friar+street+reading");
        nandosFri.setAllergenLink("https://www.nandos.co.uk/food/menu");
        nandosFri.setPhoneNum("01189511460");
        mLocations.add(nandosFri);

        RBLocation theShed = new RBLocation();
        theShed.setTitle("The Shed");
        theShed.setFoodType("Cafe Cuisine");
        theShed.setArea("Town Center");
        theShed.setIsCafe(true);
        theShed.setVegStatus(2);
        theShed.setCalStatus(3);
        theShed.setGFStatus(2);
        theShed.generateSubtitle();
        theShed.generateTypeString();
        theShed.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+shed+reading");
        theShed.setPhoneNum("01189561482");
        mLocations.add(theShed);

        RBLocation oakford = new RBLocation();
        oakford.setTitle("Oakford Social Club");
        oakford.setFoodType("Gastropub Grub");
        oakford.setArea("Town Center");
        oakford.setIsGastroPub(true);
        oakford.setVegStatus(1);
        oakford.setCalStatus(3);
        oakford.setGFStatus(2);
        oakford.generateSubtitle();
        oakford.generateTypeString();
        oakford.setMapSearch("https://www.google.com/maps/search/?api=1&query=oakford+social+club+reading");
        oakford.setPhoneNum("01189594267");
        mLocations.add(oakford);

        RBLocation malmaison = new RBLocation();
        malmaison.setTitle("Malmaison");
        malmaison.setFoodType("International");
        malmaison.setArea("Town Center");
        malmaison.setIsRestaurant(true);
        malmaison.setVegStatus(3);
        malmaison.setCalStatus(3);
        malmaison.setGFStatus(2);
        malmaison.generateSubtitle();
        malmaison.generateTypeString();
        malmaison.setMapSearch("https://www.google.com/maps/search/?api=1&query=malmaison+reading");
        malmaison.setPhoneNum("01183341331");
        mLocations.add(malmaison);

        RBLocation revs = new RBLocation();
        revs.setTitle("Revolution");
        revs.setFoodType("International");
        revs.setArea("Town Center");
        revs.setIsBar(true);
        revs.setVegStatus(2);
        revs.setCalStatus(3);
        revs.setGFStatus(1);
        revs.generateSubtitle();
        revs.generateTypeString();
        revs.setMapSearch("https://www.google.com/maps/search/?api=1&query=revolution+reading");
        revs.setAllergenLink("https://www.revolution-bars.co.uk/wp-content/uploads/2017/08/Revs_Allergen-info_Menu_AUGUST_2017_v2.pdf");
        revs.setPhoneNum("01189587397");
        mLocations.add(revs);

        RBLocation pitcher = new RBLocation();
        pitcher.setTitle("Pitcher & Piano");
        pitcher.setFoodType("International");
        pitcher.setArea("Town Center");
        pitcher.setIsBar(true);
        pitcher.setVegStatus(2);
        pitcher.setCalStatus(3);
        pitcher.setGFStatus(1);
        pitcher.generateSubtitle();
        pitcher.generateTypeString();
        pitcher.setMapSearch("https://www.google.com/maps/search/?api=1&query=pitcher+piano+reading");
        pitcher.setAllergenLink("http://www.pitcherandpiano.com/where-are-we/reading/display/documents/ss17-allergen-guide");
        pitcher.setPhoneNum("01189588964");
        mLocations.add(pitcher);

        RBLocation yates = new RBLocation();
        yates.setTitle("Yates");
        yates.setFoodType("International");
        yates.setArea("Town Center");
        yates.setIsBar(true);
        yates.setVegStatus(2);
        yates.setCalStatus(3);
        yates.setGFStatus(1);
        yates.generateSubtitle();
        yates.generateTypeString();
        yates.setMapSearch("https://www.google.com/maps/search/?api=1&query=yates+reading");
        yates.setAllergenLink("http://www.tkmenus.com/yates");
        yates.setPhoneNum("01189597090");
        mLocations.add(yates);

        RBLocation walkabout = new RBLocation();
        walkabout.setTitle("Walkabout");
        walkabout.setFoodType("International");
        walkabout.setArea("Town Center");
        walkabout.setIsBar(true);
        walkabout.setVegStatus(3);
        walkabout.setCalStatus(3);
        walkabout.setGFStatus(3);
        walkabout.generateSubtitle();
        walkabout.generateTypeString();
        walkabout.setMapSearch("https://www.google.com/maps/search/?api=1&query=walkabout+reading");
        walkabout.setPhoneNum("01189597090");
        mLocations.add(walkabout);

        RBLocation oneills = new RBLocation();
        oneills.setTitle("O'Neill's");
        oneills.setFoodType("Gastropub Grub");
        oneills.setArea("Town Center");
        oneills.setIsGastroPub(true);
        oneills.setVegStatus(1);
        oneills.setCalStatus(3);
        oneills.setGFStatus(2);
        oneills.generateSubtitle();
        oneills.generateTypeString();
        oneills.setMapSearch("https://www.google.com/maps/search/?api=1&query=oneills+reading");
        oneills.setPhoneNum("01189606580");
        mLocations.add(oneills);

        RBLocation valpy = new RBLocation();
        valpy.setTitle("Valpy");
        valpy.setFoodType("Bistro");
        valpy.setArea("Town Center");
        valpy.setIsBar(true);
        valpy.setVegStatus(1);
        valpy.setCalStatus(3);
        valpy.setGFStatus(2);
        valpy.generateSubtitle();
        valpy.generateTypeString();
        valpy.setMapSearch("https://www.google.com/maps/search/?api=1&query=valpy+reading");
        valpy.setPhoneNum("01183271331");
        mLocations.add(valpy);

        RBLocation cerise = new RBLocation();
        cerise.setTitle("Cerise");
        cerise.setFoodType("British");
        cerise.setArea("Town Center");
        cerise.setIsRestaurant(true);
        cerise.setVegStatus(3);
        cerise.setCalStatus(3);
        cerise.setGFStatus(2);
        cerise.generateSubtitle();
        cerise.generateTypeString();
        cerise.setMapSearch("https://www.google.com/maps/search/?api=1&query=cerise+reading");
        cerise.setPhoneNum("01189527770");
        mLocations.add(cerise);

        RBLocation carls = new RBLocation();
        carls.setTitle("Carluccio's");
        carls.setFoodType("Italian");
        carls.setArea("Town Center");
        carls.setIsRestaurant(true);
        carls.setVegStatus(3);
        carls.setCalStatus(3);
        carls.setGFStatus(2);
        carls.generateSubtitle();
        carls.generateTypeString();
        carls.setMapSearch("https://www.google.com/maps/search/?api=1&query=carluccios+reading");
        carls.setPhoneNum("01189583095");
        mLocations.add(carls);

        RBLocation forburys = new RBLocation();
        forburys.setTitle("Forbury's");
        forburys.setFoodType("European");
        forburys.setArea("Town Center");
        forburys.setIsRestaurant(true);
        forburys.setVegStatus(2);
        forburys.setCalStatus(3);
        forburys.setGFStatus(3);
        forburys.generateSubtitle();
        forburys.generateTypeString();
        forburys.setMapSearch("https://www.google.com/maps/search/?api=1&query=forburys+restaurant+reading");
        forburys.setPhoneNum("01189574044");
        mLocations.add(forburys);

        RBLocation bills = new RBLocation();
        bills.setTitle("Bill's");
        bills.setFoodType("European");
        bills.setArea("Town Center");
        bills.setIsRestaurant(true);
        bills.setVegStatus(1);
        bills.setCalStatus(1);
        bills.setGFStatus(1);
        bills.generateSubtitle();
        bills.generateTypeString();
        bills.setMapSearch("https://www.google.com/maps/search/?api=1&query=bills+reading");
        bills.setAllergenLink("https://d1k0w6lyhojuj5.cloudfront.net/wp-content/uploads/2013/06/04190003/Bills-Allergens-Core-Menu_sep_18_LSM_LORES.pdf");
        bills.setPhoneNum("01189391365");
        mLocations.add(bills);

        RBLocation pizzaExpM = new RBLocation();
        pizzaExpM.setTitle("Pizza Express (St Mary's)");
        pizzaExpM.setFoodType("Italian");
        pizzaExpM.setArea("Town Center");
        pizzaExpM.setIsRestaurant(true);
        pizzaExpM.setVegStatus(2);
        pizzaExpM.setCalStatus(2);
        pizzaExpM.setGFStatus(1);
        pizzaExpM.generateSubtitle();
        pizzaExpM.generateTypeString();
        pizzaExpM.setMapSearch("https://www.google.com/maps/search/?api=1&query=pizza+express+st+marys+reading");
        pizzaExpM.setAllergenLink("https://www.pizzaexpress.com/~/media/files/pdfs/nutritionals/pex_allergens-our-food.ashx");
        pizzaExpM.setPhoneNum("01189391920");
        mLocations.add(pizzaExpM);

        RBLocation boneBurger = new RBLocation();
        boneBurger.setTitle("7bone Burger Co");
        boneBurger.setFoodType("American");
        boneBurger.setArea("Town Center");
        boneBurger.setIsRestaurant(true);
        boneBurger.setVegStatus(2);
        boneBurger.setCalStatus(3);
        boneBurger.setGFStatus(1);
        boneBurger.generateSubtitle();
        boneBurger.generateTypeString();
        boneBurger.setMapSearch("https://www.google.com/maps/search/?api=1&query=7bone+burger+reading");
        boneBurger.setAllergenLink("http://www.7bone.co.uk/allergies.php");
        boneBurger.setPhoneNum("01189952094");
        mLocations.add(boneBurger);

        RBLocation smokinBillys = new RBLocation();
        smokinBillys.setTitle("Smokin' Billy's");
        smokinBillys.setFoodType("American");
        smokinBillys.setArea("Town Center");
        smokinBillys.setIsRestaurant(true);
        smokinBillys.setVegStatus(3);
        smokinBillys.setCalStatus(3);
        smokinBillys.setGFStatus(2);
        smokinBillys.generateSubtitle();
        smokinBillys.generateTypeString();
        smokinBillys.setMapSearch("https://www.google.com/maps/search/?api=1&query=smokin+billys+reading");
        smokinBillys.setPhoneNum("01189573500");
        mLocations.add(smokinBillys);

        RBLocation coconut = new RBLocation();
        coconut.setTitle("Coconut");
        coconut.setFoodType("Asian");
        coconut.setArea("Town Center");
        coconut.setIsRestaurant(true);
        coconut.setVegStatus(2);
        coconut.setCalStatus(3);
        coconut.setGFStatus(2);
        coconut.generateSubtitle();
        coconut.generateTypeString();
        coconut.setMapSearch("https://www.google.com/maps/search/?api=1&query=coconut+reading");
        coconut.setPhoneNum("01189598877");
        mLocations.add(coconut);

        RBLocation ask = new RBLocation();
        ask.setTitle("ASK");
        ask.setFoodType("Italian");
        ask.setArea("Town Center");
        ask.setIsRestaurant(true);
        ask.setVegStatus(1);
        ask.setCalStatus(3);
        ask.setGFStatus(1);
        ask.generateSubtitle();
        ask.generateTypeString();
        ask.setMapSearch("https://www.google.com/maps/search/?api=1&query=ask+reading");
        ask.setAllergenLink("https://www.askitalian.co.uk/media/2216/170614-allergenmenu-15-september-17.pdf");
        ask.setPhoneNum("01189574850");
        mLocations.add(ask);

        RBLocation wolfBS = new RBLocation();
        wolfBS.setTitle("Wolf (Broad St)");
        wolfBS.setFoodType("Italian");
        wolfBS.setArea("Town Center");
        wolfBS.setIsRestaurant(true);
        wolfBS.setVegStatus(2);
        wolfBS.setCalStatus(3);
        wolfBS.setGFStatus(3);
        wolfBS.generateSubtitle();
        wolfBS.generateTypeString();
        wolfBS.setMapSearch("https://www.google.com/maps/search/?api=1&query=wolf+broad+street+reading");
        wolfBS.setPhoneNum("01189598179");
        mLocations.add(wolfBS);

        RBLocation munchees = new RBLocation();
        munchees.setTitle("Munchees");
        munchees.setFoodType("Indian/Nepalese");
        munchees.setArea("Town Center");
        munchees.setIsRestaurant(true);
        munchees.setVegStatus(2);
        munchees.setCalStatus(3);
        munchees.setGFStatus(3);
        munchees.generateSubtitle();
        munchees.generateTypeString();
        munchees.setMapSearch("https://www.google.com/maps/search/?api=1&query=munchees+reading");
        munchees.setPhoneNum("01189573708");
        mLocations.add(munchees);

        RBLocation nibsys = new RBLocation();
        nibsys.setTitle("Nibsy's");
        nibsys.setFoodType("Cafe Cuisine");
        nibsys.setArea("Town Center");
        nibsys.setIsCafe(true);
        nibsys.setVegStatus(1);
        nibsys.setCalStatus(3);
        nibsys.setGFStatus(1);
        nibsys.generateSubtitle();
        nibsys.generateTypeString();
        nibsys.setMapSearch("https://www.google.com/maps/search/?api=1&query=nibsys+reading");
        nibsys.setPhoneNum("01189597809");
        mLocations.add(nibsys);

        RBLocation itsu = new RBLocation();
        itsu.setTitle("Itsu");
        itsu.setFoodType("Japanese");
        itsu.setArea("Town Center");
        itsu.setIsRestaurant(true);
        itsu.setVegStatus(1);
        itsu.setCalStatus(1);
        itsu.setGFStatus(1);
        itsu.generateSubtitle();
        itsu.generateTypeString();
        itsu.setMapSearch("https://www.google.com/maps/search/?api=1&query=itsu+reading");
        itsu.setAllergenLink("https://www.itsu.com/menu");
        itsu.setPhoneNum("01184020979");
        mLocations.add(itsu);

        RBLocation kokoro = new RBLocation();
        kokoro.setTitle("Kokoro");
        kokoro.setFoodType("Japanese");
        kokoro.setArea("Town Center");
        kokoro.setIsRestaurant(true);
        kokoro.setVegStatus(2);
        kokoro.setCalStatus(3);
        kokoro.setGFStatus(3);
        kokoro.generateSubtitle();
        kokoro.generateTypeString();
        kokoro.setMapSearch("https://www.google.com/maps/search/?api=1&query=kokoro+reading");
        kokoro.setPhoneNum("07939507828");
        mLocations.add(kokoro);

        RBLocation pretBroad = new RBLocation();
        pretBroad.setTitle("Pret A Manger (Broad St)");
        pretBroad.setFoodType("Cafe Cuisine");
        pretBroad.setArea("Town Center");
        pretBroad.setIsCafe(true);
        pretBroad.setVegStatus(1);
        pretBroad.setCalStatus(1);
        pretBroad.setGFStatus(1);
        pretBroad.generateSubtitle();
        pretBroad.generateTypeString();
        pretBroad.setMapSearch("https://www.google.com/maps/search/?api=1&query=pret+broad+street+reading");
        pretBroad.setAllergenLink("https://odcdn2.zenedge.com/pretamanger-uk/allergen-guide/Allergen%20Guide%20130717.pdf");
        pretBroad.setPhoneNum("01189391802");
        mLocations.add(pretBroad);

        RBLocation pavs = new RBLocation();
        pavs.setTitle("Pavlov's Dog");
        pavs.setFoodType("Gastropub Grub");
        pavs.setArea("Town Center");
        pavs.setIsGastroPub(true);
        pavs.setVegStatus(1);
        pavs.setCalStatus(3);
        pavs.setGFStatus(2);
        pavs.generateSubtitle();
        pavs.generateTypeString();
        pavs.setMapSearch("https://www.google.com/maps/search/?api=1&query=pavlovs+dog+reading");
        pavs.setPhoneNum("01189519001");
        mLocations.add(pavs);

        RBLocation thaiCorner = new RBLocation();
        thaiCorner.setTitle("Thai Corner");
        thaiCorner.setFoodType("Thai");
        thaiCorner.setArea("Town Center");
        thaiCorner.setIsRestaurant(true);
        thaiCorner.setVegStatus(2);
        thaiCorner.setCalStatus(3);
        thaiCorner.setGFStatus(3);
        thaiCorner.generateSubtitle();
        thaiCorner.generateTypeString();
        thaiCorner.setMapSearch("https://www.google.com/maps/search/?api=1&query=thai+corner+reading");
        thaiCorner.setPhoneNum("01189595050");
        mLocations.add(thaiCorner);

        RBLocation theBotanist = new RBLocation();
        theBotanist.setTitle("The Botanist");
        theBotanist.setFoodType("Upscale Gastro");
        theBotanist.setArea("Town Center");
        theBotanist.setIsBar(true);
        theBotanist.setVegStatus(3);
        theBotanist.setCalStatus(3);
        theBotanist.setGFStatus(2);
        theBotanist.generateSubtitle();
        theBotanist.generateTypeString();
        theBotanist.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+botanist+reading");
        theBotanist.setPhoneNum("01189595749");
        mLocations.add(theBotanist);

        RBLocation chinaPalace = new RBLocation();
        chinaPalace.setTitle("China Palace");
        chinaPalace.setFoodType("Chinese");
        chinaPalace.setArea("Broad Street Mall");
        chinaPalace.setIsRestaurant(true);
        chinaPalace.setVegStatus(2);
        chinaPalace.setCalStatus(3);
        chinaPalace.setGFStatus(3);
        chinaPalace.generateSubtitle();
        chinaPalace.generateTypeString();
        chinaPalace.setMapSearch("https://www.google.com/maps/search/?api=1&query=china+palace+reading");
        chinaPalace.setPhoneNum("01189572323");
        mLocations.add(chinaPalace);

        RBLocation sushiMania = new RBLocation();
        sushiMania.setTitle("Sushi Mania");
        sushiMania.setFoodType("Japanese");
        sushiMania.setArea("Broad Street Mall");
        sushiMania.setIsRestaurant(true);
        sushiMania.setVegStatus(2);
        sushiMania.setCalStatus(3);
        sushiMania.setGFStatus(3);
        sushiMania.generateSubtitle();
        sushiMania.generateTypeString();
        sushiMania.setMapSearch("https://www.google.com/maps/search/?api=1&query=sushi+mania+reading");
        sushiMania.setPhoneNum("01189588293");
        mLocations.add(sushiMania);

        RBLocation pepeSale = new RBLocation();
        pepeSale.setTitle("Pepe Sale");
        pepeSale.setFoodType("Italian");
        pepeSale.setArea("Broad Street Mall");
        pepeSale.setIsRestaurant(true);
        pepeSale.setVegStatus(2);
        pepeSale.setCalStatus(3);
        pepeSale.setGFStatus(3);
        pepeSale.generateSubtitle();
        pepeSale.generateTypeString();
        pepeSale.setMapSearch("https://www.google.com/maps/search/?api=1&query=pepe+sale+reading");
        pepeSale.setPhoneNum("01189597700");
        mLocations.add(pepeSale);

        RBLocation tgisCavRoad = new RBLocation();
        tgisCavRoad.setTitle("TGI Fridays (Caversham Rd)");
        tgisCavRoad.setFoodType("American");
        tgisCavRoad.setArea("Central Reading");
        tgisCavRoad.setIsRestaurant(true);
        tgisCavRoad.setVegStatus(1);
        tgisCavRoad.setCalStatus(3);
        tgisCavRoad.setGFStatus(1);
        tgisCavRoad.generateSubtitle();
        tgisCavRoad.generateTypeString();
        tgisCavRoad.setMapSearch("https://www.google.com/maps/search/?api=1&query=tgi+fridays+caversham+road+reading");
        tgisCavRoad.setAllergenLink("https://www.tgifridays.co.uk/reading/the-grill/#allergy-menu");
        tgisCavRoad.setPhoneNum("03446920231");
        mLocations.add(tgisCavRoad);

        RBLocation belDragon = new RBLocation();
        belDragon.setTitle("Bel & The Dragon");
        belDragon.setFoodType("Upscale Gastro");
        belDragon.setArea("Central Reading");
        belDragon.setIsRestaurant(true);
        belDragon.setVegStatus(3);
        belDragon.setCalStatus(3);
        belDragon.setGFStatus(2);
        belDragon.generateSubtitle();
        belDragon.generateTypeString();
        belDragon.setMapSearch("https://www.google.com/maps/search/?api=1&query=bel+and+the+dragon+reading");
        belDragon.setPhoneNum("01189515790");
        mLocations.add(belDragon);

        RBLocation thirstyBear = new RBLocation();
        thirstyBear.setTitle("Thirsty Bear");
        thirstyBear.setFoodType("Italian");
        thirstyBear.setArea("Central Reading");
        thirstyBear.setIsRestaurant(true);
        thirstyBear.setVegStatus(2);
        thirstyBear.setCalStatus(3);
        thirstyBear.setGFStatus(3);
        thirstyBear.generateSubtitle();
        thirstyBear.generateTypeString();
        thirstyBear.setMapSearch("https://www.google.com/maps/search/?api=1&query=thirsty+bear+reading");
        thirstyBear.setPhoneNum("01189504439");
        mLocations.add(thirstyBear);

        RBLocation backOfBeyond = new RBLocation();
        backOfBeyond.setTitle("Back Of Beyond");
        backOfBeyond.setFoodType("Gastropub Grub");
        backOfBeyond.setArea("Central Reading");
        backOfBeyond.setIsGastroPub(true);
        backOfBeyond.setVegStatus(1);
        backOfBeyond.setCalStatus(1);
        backOfBeyond.setGFStatus(1);
        backOfBeyond.generateSubtitle();
        backOfBeyond.generateTypeString();
        backOfBeyond.setMapSearch("https://www.google.com/maps/search/?api=1&query=back+of+beyond+reading");
        backOfBeyond.setAllergenLink("https://www.jdwetherspoon.com/food/menu?pub=e4f06ff959b84ed295eefb34d21db2cd");
        backOfBeyond.setPhoneNum("01189595906");
        mLocations.add(backOfBeyond);

        RBLocation baliLounge = new RBLocation();
        baliLounge.setTitle("Bali Lounge");
        baliLounge.setFoodType("Thai");
        baliLounge.setArea("Central Reading");
        baliLounge.setIsRestaurant(true);
        baliLounge.setVegStatus(2);
        baliLounge.setCalStatus(3);
        baliLounge.setGFStatus(2);
        baliLounge.generateSubtitle();
        baliLounge.generateTypeString();
        baliLounge.setMapSearch("https://www.google.com/maps/search/?api=1&query=bali+lounge+reading");
        baliLounge.setPhoneNum("01189566969");
        mLocations.add(baliLounge);

        RBLocation theOutlook = new RBLocation();
        theOutlook.setTitle("The Outlook");
        theOutlook.setFoodType("Gastropub Grub");
        theOutlook.setArea("Central Reading");
        theOutlook.setIsGastroPub(true);
        theOutlook.setVegStatus(1);
        theOutlook.setCalStatus(3);
        theOutlook.setGFStatus(3);
        theOutlook.generateSubtitle();
        theOutlook.generateTypeString();
        theOutlook.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+outlook+reading");
        theOutlook.setPhoneNum("01189586549");
        mLocations.add(theOutlook);

        RBLocation zizzi = new RBLocation();
        zizzi.setTitle("Zizzi");
        zizzi.setFoodType("Italian");
        zizzi.setArea("Central Reading");
        zizzi.setIsRestaurant(true);
        zizzi.setVegStatus(1);
        zizzi.setCalStatus(2);
        zizzi.setGFStatus(1);
        zizzi.generateSubtitle();
        zizzi.generateTypeString();
        zizzi.setMapSearch("https://www.google.com/maps/search/?api=1&query=zizzi+reading");
        zizzi.setPhoneNum("01189594662");
        mLocations.add(zizzi);

        RBLocation pappadams = new RBLocation();
        pappadams.setTitle("Pappadams");
        pappadams.setFoodType("Indian");
        pappadams.setArea("Central Reading");
        pappadams.setIsRestaurant(true);
        pappadams.setVegStatus(2);
        pappadams.setCalStatus(3);
        pappadams.setGFStatus(3);
        pappadams.generateSubtitle();
        pappadams.generateTypeString();
        pappadams.setMapSearch("https://www.google.com/maps/search/?api=1&query=pappadams+reading");
        pappadams.setPhoneNum("01189585111");
        mLocations.add(pappadams);

        RBLocation houseOfFlavours = new RBLocation();
        houseOfFlavours.setTitle("House Of Flavours");
        houseOfFlavours.setFoodType("Indian/Nepalese");
        houseOfFlavours.setArea("Central Reading");
        houseOfFlavours.setIsRestaurant(true);
        houseOfFlavours.setVegStatus(2);
        houseOfFlavours.setCalStatus(3);
        houseOfFlavours.setGFStatus(3);
        houseOfFlavours.generateSubtitle();
        houseOfFlavours.generateTypeString();
        houseOfFlavours.setMapSearch("https://www.google.com/maps/search/?api=1&query=house+of+flavours+reading");
        houseOfFlavours.setPhoneNum("01189503500");
        mLocations.add(houseOfFlavours);

        RBLocation bakeryHouse = new RBLocation();
        bakeryHouse.setTitle("Bakery House");
        bakeryHouse.setFoodType("Lebanese");
        bakeryHouse.setArea("Central Reading");
        bakeryHouse.setIsRestaurant(true);
        bakeryHouse.setVegStatus(2);
        bakeryHouse.setCalStatus(3);
        bakeryHouse.setGFStatus(1);
        bakeryHouse.generateSubtitle();
        bakeryHouse.generateTypeString();
        bakeryHouse.setMapSearch("https://www.google.com/maps/search/?api=1&query=bakery+house+reading");
        bakeryHouse.setPhoneNum("01183274040");
        mLocations.add(bakeryHouse);

        RBLocation theLyndhurst = new RBLocation();
        theLyndhurst.setTitle("The Lyndhurst");
        theLyndhurst.setFoodType("British");
        theLyndhurst.setArea("Central Reading");
        theLyndhurst.setIsGastroPub(true);
        theLyndhurst.setVegStatus(1);
        theLyndhurst.setCalStatus(3);
        theLyndhurst.setGFStatus(3);
        theLyndhurst.generateSubtitle();
        theLyndhurst.generateTypeString();
        theLyndhurst.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+lyndhurst+reading");
        theLyndhurst.setPhoneNum("01189503888");
        mLocations.add(theLyndhurst);

        RBLocation abbotCook = new RBLocation();
        abbotCook.setTitle("The Abbot Cook");
        abbotCook.setFoodType("Gastropub Grub");
        abbotCook.setArea("Central Reading");
        abbotCook.setIsGastroPub(true);
        abbotCook.setVegStatus(1);
        abbotCook.setCalStatus(3);
        abbotCook.setGFStatus(1);
        abbotCook.generateSubtitle();
        abbotCook.generateTypeString();
        abbotCook.setMapSearch("https://www.google.com/maps/search/?api=1&query=abbot+cook+reading");
        abbotCook.setAllergenLink("https://smartchef.azurewebsites.net/Brands/CastleWorkRestStretch");
        abbotCook.setPhoneNum("01189354095");
        mLocations.add(abbotCook);

        RBLocation gooiNara = new RBLocation();
        gooiNara.setTitle("Gooi Nara");
        gooiNara.setFoodType("Korean BBQ");
        gooiNara.setArea("Central Reading");
        gooiNara.setIsRestaurant(true);
        gooiNara.setVegStatus(2);
        gooiNara.setCalStatus(3);
        gooiNara.setGFStatus(2);
        gooiNara.generateSubtitle();
        gooiNara.generateTypeString();
        gooiNara.setMapSearch("https://www.google.com/maps/search/?api=1&query=gooi+nara+reading");
        gooiNara.setPhoneNum("01189757889");
        mLocations.add(gooiNara);

        RBLocation namasteKitchen = new RBLocation();
        namasteKitchen.setTitle("Namaste Kitchen");
        namasteKitchen.setFoodType("Indian/Nepalese");
        namasteKitchen.setArea("Central Reading");
        namasteKitchen.setIsRestaurant(true);
        namasteKitchen.setVegStatus(2);
        namasteKitchen.setCalStatus(3);
        namasteKitchen.setGFStatus(3);
        namasteKitchen.generateSubtitle();
        namasteKitchen.generateTypeString();
        namasteKitchen.setMapSearch("https://www.google.com/maps/search/?api=1&query=namaste+kitchen+reading");
        namasteKitchen.setPhoneNum("01189594617");
        mLocations.add(namasteKitchen);

        RBLocation sprinklesGelato = new RBLocation();
        sprinklesGelato.setTitle("Sprinkles Gelato");
        sprinklesGelato.setFoodType("Desserts & Sweets");
        sprinklesGelato.setArea("Central Reading");
        sprinklesGelato.setIsDessertBar(true);
        sprinklesGelato.setVegStatus(1);
        sprinklesGelato.setCalStatus(3);
        sprinklesGelato.setGFStatus(1);
        sprinklesGelato.generateSubtitle();
        sprinklesGelato.generateTypeString();
        sprinklesGelato.setMapSearch("https://www.google.com/maps/search/?api=1&query=sprinkles+gelato+reading");
        sprinklesGelato.setPhoneNum("01189263692");
        mLocations.add(sprinklesGelato);

        RBLocation cafeYolk = new RBLocation();
        cafeYolk.setTitle("Cafe Yolk");
        cafeYolk.setFoodType("All Day Breakfast");
        cafeYolk.setArea("Central Reading");
        cafeYolk.setIsCafe(true);
        cafeYolk.setVegStatus(2);
        cafeYolk.setCalStatus(3);
        cafeYolk.setGFStatus(3);
        cafeYolk.generateSubtitle();
        cafeYolk.generateTypeString();
        cafeYolk.setMapSearch("https://www.google.com/maps/search/?api=1&query=cafe+yolk+reading");
        cafeYolk.setPhoneNum("01183271055");
        mLocations.add(cafeYolk);

        RBLocation chinaGarden = new RBLocation();
        chinaGarden.setTitle("China Garden");
        chinaGarden.setFoodType("Chinese");
        chinaGarden.setArea("South Reading");
        chinaGarden.setIsRestaurant(true);
        chinaGarden.setVegStatus(2);
        chinaGarden.setCalStatus(3);
        chinaGarden.setGFStatus(3);
        chinaGarden.generateSubtitle();
        chinaGarden.generateTypeString();
        chinaGarden.setMapSearch("https://www.google.com/maps/search/?api=1&query=china+garden+reading");
        chinaGarden.setPhoneNum("01189313268");
        mLocations.add(chinaGarden);

        RBLocation sizzlingSpice = new RBLocation();
        sizzlingSpice.setTitle("Sizzling Spice");
        sizzlingSpice.setFoodType("Indian");
        sizzlingSpice.setArea("South Reading");
        sizzlingSpice.setIsRestaurant(true);
        sizzlingSpice.setVegStatus(2);
        sizzlingSpice.setCalStatus(3);
        sizzlingSpice.setGFStatus(2);
        sizzlingSpice.generateSubtitle();
        sizzlingSpice.generateTypeString();
        sizzlingSpice.setMapSearch("https://www.google.com/maps/search/?api=1&query=sizzling+spice+reading");
        sizzlingSpice.setPhoneNum("01189871190");
        mLocations.add(sizzlingSpice);

        RBLocation wolfGP = new RBLocation();
        wolfGP.setTitle("Wolf (Green Park)");
        wolfGP.setFoodType("Italian");
        wolfGP.setArea("South Reading");
        wolfGP.setIsRestaurant(true);
        wolfGP.setVegStatus(2);
        wolfGP.setCalStatus(3);
        wolfGP.setGFStatus(3);
        wolfGP.generateSubtitle();
        wolfGP.generateTypeString();
        wolfGP.setMapSearch("https://www.google.com/maps/search/?api=1&query=wolf+green+park+oak+way+reading");
        wolfGP.setPhoneNum("01189868892");
        mLocations.add(wolfGP);

        RBLocation zest = new RBLocation();
        zest.setTitle("Zest (Green Park)");
        zest.setFoodType("International");
        zest.setArea("South Reading");
        zest.setIsRestaurant(true);
        zest.setVegStatus(2);
        zest.setCalStatus(3);
        zest.setGFStatus(1);
        zest.generateSubtitle();
        zest.generateTypeString();
        zest.setMapSearch("https://www.google.com/maps/search/?api=1&query=zest+lime+square+reading");
        zest.setPhoneNum("01189873702");
        mLocations.add(zest);

        RBLocation cunningMan = new RBLocation();
        cunningMan.setTitle("The Cunning Man");
        cunningMan.setFoodType("Gastropub Grub");
        cunningMan.setArea("South Reading");
        cunningMan.setIsGastroPub(true);
        cunningMan.setVegStatus(2);
        cunningMan.setCalStatus(3);
        cunningMan.setGFStatus(2);
        cunningMan.generateSubtitle();
        cunningMan.generateTypeString();
        cunningMan.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+cunning+man+reading");
        cunningMan.setPhoneNum("01189598067");
        mLocations.add(cunningMan);

        RBLocation dhaulagiriKitchen = new RBLocation();
        dhaulagiriKitchen.setTitle("Dhaulagiri Kitchen");
        dhaulagiriKitchen.setFoodType("Indian/Nepalese");
        dhaulagiriKitchen.setArea("South Reading");
        dhaulagiriKitchen.setIsRestaurant(true);
        dhaulagiriKitchen.setVegStatus(2);
        dhaulagiriKitchen.setCalStatus(3);
        dhaulagiriKitchen.setGFStatus(2);
        dhaulagiriKitchen.generateSubtitle();
        dhaulagiriKitchen.generateTypeString();
        dhaulagiriKitchen.setMapSearch("https://www.google.com/maps/search/?api=1&query=dhaulagiri+kitchen+reading");
        dhaulagiriKitchen.setPhoneNum("01189759898");
        mLocations.add(dhaulagiriKitchen);

        RBLocation theWorldTurnedUpsideDown = new RBLocation();
        theWorldTurnedUpsideDown.setTitle("The World Turned Upside Down");
        theWorldTurnedUpsideDown.setFoodType("Pizza & Carvery");
        theWorldTurnedUpsideDown.setArea("South Reading");
        theWorldTurnedUpsideDown.setIsRestaurant(true);
        theWorldTurnedUpsideDown.setVegStatus(1);
        theWorldTurnedUpsideDown.setCalStatus(1);
        theWorldTurnedUpsideDown.setGFStatus(1);
        theWorldTurnedUpsideDown.generateSubtitle();
        theWorldTurnedUpsideDown.generateTypeString();
        theWorldTurnedUpsideDown.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+world+turned+upside+down+reading");
        theWorldTurnedUpsideDown.setAllergenLink("https://smartchef.azurewebsites.net/Brands/Stonehouse");
        theWorldTurnedUpsideDown.setPhoneNum("01189871763");
        mLocations.add(theWorldTurnedUpsideDown);

        RBLocation theQueensHead = new RBLocation();
        theQueensHead.setTitle("The Queen's Head");
        theQueensHead.setFoodType("Gastropub Grub");
        theQueensHead.setArea("South Reading");
        theQueensHead.setIsGastroPub(true);
        theQueensHead.setVegStatus(2);
        theQueensHead.setCalStatus(3);
        theQueensHead.setGFStatus(2);
        theQueensHead.generateSubtitle();
        theQueensHead.generateTypeString();
        theQueensHead.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+queens+head+reading");
        theQueensHead.setPhoneNum("01189863040");
        mLocations.add(theQueensHead);

        RBLocation anatolia = new RBLocation();
        anatolia.setTitle("Anatolia");
        anatolia.setFoodType("Mediterranean");
        anatolia.setArea("West Reading");
        anatolia.setIsRestaurant(true);
        anatolia.setVegStatus(3);
        anatolia.setCalStatus(3);
        anatolia.setGFStatus(3);
        anatolia.generateSubtitle();
        anatolia.generateTypeString();
        anatolia.setMapSearch("https://www.google.com/maps/search/?api=1&query=anatolia+reading");
        anatolia.setPhoneNum("01189560070");
        mLocations.add(anatolia);

        RBLocation readingTandoori = new RBLocation();
        readingTandoori.setTitle("Reading Tandoori");
        readingTandoori.setFoodType("Indian/Nepalese");
        readingTandoori.setArea("West Reading");
        readingTandoori.setIsRestaurant(true);
        readingTandoori.setVegStatus(3);
        readingTandoori.setCalStatus(3);
        readingTandoori.setGFStatus(3);
        readingTandoori.generateSubtitle();
        readingTandoori.generateTypeString();
        readingTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=reading+tandoori+reading");
        readingTandoori.setPhoneNum("01189500524");
        mLocations.add(readingTandoori);

        RBLocation buonAppetito = new RBLocation();
        buonAppetito.setTitle("Buon Appetito");
        buonAppetito.setFoodType("Italian");
        buonAppetito.setArea("West Reading");
        buonAppetito.setIsRestaurant(true);
        buonAppetito.setVegStatus(2);
        buonAppetito.setCalStatus(3);
        buonAppetito.setGFStatus(3);
        buonAppetito.generateSubtitle();
        buonAppetito.generateTypeString();
        buonAppetito.setMapSearch("https://www.google.com/maps/search/?api=1&query=buon+appetito+reading");
        buonAppetito.setPhoneNum("01183273390");
        mLocations.add(buonAppetito);

        RBLocation beefeaterSouthcote = new RBLocation();
        beefeaterSouthcote.setTitle("Beefeater Southcote");
        beefeaterSouthcote.setFoodType("Steak House");
        beefeaterSouthcote.setArea("West Reading");
        beefeaterSouthcote.setIsRestaurant(true);
        beefeaterSouthcote.setVegStatus(1);
        beefeaterSouthcote.setCalStatus(3);
        beefeaterSouthcote.setGFStatus(3);
        beefeaterSouthcote.generateSubtitle();
        beefeaterSouthcote.generateTypeString();
        beefeaterSouthcote.setMapSearch("https://www.google.com/maps/search/?api=1&query=beefeater+southcote+reading");
        beefeaterSouthcote.setPhoneNum("01189572685");
        mLocations.add(beefeaterSouthcote);

        RBLocation riverSpice = new RBLocation();
        riverSpice.setTitle("River Spice");
        riverSpice.setFoodType("Indian/Nepalese");
        riverSpice.setArea("North Reading");
        riverSpice.setIsRestaurant(true);
        riverSpice.setVegStatus(3);
        riverSpice.setCalStatus(3);
        riverSpice.setGFStatus(3);
        riverSpice.generateSubtitle();
        riverSpice.generateTypeString();
        riverSpice.setMapSearch("https://www.google.com/maps/search/?api=1&query=river+spice+reading");
        riverSpice.setPhoneNum("01189503355");
        mLocations.add(riverSpice);

        RBLocation richfieldsDeli = new RBLocation();
        richfieldsDeli.setTitle("Richfields Deli &  Grill");
        richfieldsDeli.setFoodType("Street Food");
        richfieldsDeli.setArea("North Reading");
        richfieldsDeli.setIsRestaurant(true);
        richfieldsDeli.setVegStatus(1);
        richfieldsDeli.setCalStatus(3);
        richfieldsDeli.setGFStatus(3);
        richfieldsDeli.generateSubtitle();
        richfieldsDeli.generateTypeString();
        richfieldsDeli.setMapSearch("https://www.google.com/maps/search/?api=1&query=richfields+deli+reading");
        richfieldsDeli.setPhoneNum("01189391144");
        mLocations.add(richfieldsDeli);

        RBLocation theModeration = new RBLocation();
        theModeration.setTitle("The Moderation");
        theModeration.setFoodType("Gastropub Grub");
        theModeration.setArea("North Reading");
        theModeration.setIsGastroPub(true);
        theModeration.setVegStatus(2);
        theModeration.setCalStatus(3);
        theModeration.setGFStatus(3);
        theModeration.generateSubtitle();
        theModeration.generateTypeString();
        theModeration.setMapSearch("https://www.google.com/maps/search/?api=1&query=the+moderation+reading");
        theModeration.setPhoneNum("01183750767");
        mLocations.add(theModeration);

        RBLocation standardTandoori = new RBLocation();
        standardTandoori.setTitle("Standard Tandoori");
        standardTandoori.setFoodType("Indian/Nepalese");
        standardTandoori.setArea("North Reading");
        standardTandoori.setIsRestaurant(true);
        standardTandoori.setVegStatus(2);
        standardTandoori.setCalStatus(3);
        standardTandoori.setGFStatus(3);
        standardTandoori.generateSubtitle();
        standardTandoori.generateTypeString();
        standardTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=standard+tandoori+reading");
        standardTandoori.setPhoneNum("01189590093");
        mLocations.add(standardTandoori);

        RBLocation cozze = new RBLocation();
        cozze.setTitle("Cozze");
        cozze.setFoodType("Italian");
        cozze.setArea("North Reading");
        cozze.setIsRestaurant(true);
        cozze.setVegStatus(2);
        cozze.setCalStatus(3);
        cozze.setGFStatus(2);
        cozze.generateSubtitle();
        cozze.generateTypeString();
        cozze.setMapSearch("https://www.google.com/maps/search/?api=1&query=cozze+caversham+road");
        cozze.setPhoneNum("01189591459");
        mLocations.add(cozze);

        RBLocation cavershamRose = new RBLocation();
        cavershamRose.setTitle("The Caversham Rose");
        cavershamRose.setFoodType("Gastropub Grub");
        cavershamRose.setArea("Caversham");
        cavershamRose.setIsGastroPub(true);
        cavershamRose.setVegStatus(2);
        cavershamRose.setCalStatus(2);
        cavershamRose.setGFStatus(2);
        cavershamRose.generateSubtitle();
        cavershamRose.generateTypeString();
        cavershamRose.setMapSearch("https://www.google.com/maps/search/?api=1&query=caversham+rose+reading");
        cavershamRose.setAllergenLink("https://smartchef.azurewebsites.net/brands/pcp");
        cavershamRose.setPhoneNum("01189474643");
        mLocations.add(cavershamRose);

        RBLocation picasso = new RBLocation();
        picasso.setTitle("Picasso");
        picasso.setFoodType("Tapas");
        picasso.setArea("Caversham");
        picasso.setIsRestaurant(true);
        picasso.setVegStatus(3);
        picasso.setCalStatus(3);
        picasso.setGFStatus(3);
        picasso.generateSubtitle();
        picasso.generateTypeString();
        picasso.setMapSearch("https://www.google.com/maps/search/?api=1&query=picasso+reading");
        picasso.setPhoneNum("01189484141");
        mLocations.add(picasso);

        RBLocation thaiTable = new RBLocation();
        thaiTable.setTitle("Thai Table");
        thaiTable.setFoodType("Thai");
        thaiTable.setArea("Caversham");
        thaiTable.setIsRestaurant(true);
        thaiTable.setVegStatus(2);
        thaiTable.setCalStatus(3);
        thaiTable.setGFStatus(1);
        thaiTable.generateSubtitle();
        thaiTable.generateTypeString();
        thaiTable.setMapSearch("https://www.google.com/maps/search/?api=1&query=thai+table+reading");
        thaiTable.setPhoneNum("01189471500");
        mLocations.add(thaiTable);

        RBLocation griffin = new RBLocation();
        griffin.setTitle("Griffin");
        griffin.setFoodType("Gastropub Grub");
        griffin.setArea("Caversham");
        griffin.setIsGastroPub(true);
        griffin.setVegStatus(1);
        griffin.setCalStatus(3);
        griffin.setGFStatus(2);
        griffin.generateSubtitle();
        griffin.generateTypeString();
        griffin.setMapSearch("https://www.google.com/maps/search/?api=1&query=griffin+reading");
        griffin.setPhoneNum("01189475018");
        mLocations.add(griffin);

        RBLocation spiceOven = new RBLocation();
        spiceOven.setTitle("Spice Oven");
        spiceOven.setFoodType("Indian/Nepalese");
        spiceOven.setArea("Caversham");
        spiceOven.setIsRestaurant(true);
        spiceOven.setVegStatus(1);
        spiceOven.setCalStatus(3);
        spiceOven.setGFStatus(2);
        spiceOven.generateSubtitle();
        spiceOven.generateTypeString();
        spiceOven.setMapSearch("https://www.google.com/maps/search/?api=1&query=spice+oven+reading");
        spiceOven.setAllergenLink("http://www.spiceoven.co.uk/spice_oven_restaurant_reading_takeaway.php");
        spiceOven.setPhoneNum("01189481000");
        mLocations.add(spiceOven);

        RBLocation altoLounge = new RBLocation();
        altoLounge.setTitle("Alto Lounge");
        altoLounge.setFoodType("World Cuisine");
        altoLounge.setArea("Caversham");
        altoLounge.setIsRestaurant(true);
        altoLounge.setVegStatus(1);
        altoLounge.setCalStatus(3);
        altoLounge.setGFStatus(1);
        altoLounge.generateSubtitle();
        altoLounge.generateTypeString();
        altoLounge.setMapSearch("https://www.google.com/maps/search/?api=1&query=alto+lounge+reading");
        altoLounge.setPhoneNum("01189473522");
        mLocations.add(altoLounge);

        RBLocation kyrenia = new RBLocation();
        kyrenia.setTitle("Kyrenia");
        kyrenia.setFoodType("Greek");
        kyrenia.setArea("Caversham");
        kyrenia.setIsRestaurant(true);
        kyrenia.setVegStatus(2);
        kyrenia.setCalStatus(3);
        kyrenia.setGFStatus(3);
        kyrenia.generateSubtitle();
        kyrenia.generateTypeString();
        kyrenia.setMapSearch("https://www.google.com/maps/search/?api=1&query=kyrenia+reading");
        kyrenia.setPhoneNum("01189476444");
        mLocations.add(kyrenia);

        RBLocation quattro = new RBLocation();
        quattro.setTitle("Quattro");
        quattro.setFoodType("Italian");
        quattro.setArea("Caversham");
        quattro.setIsRestaurant(true);
        quattro.setVegStatus(2);
        quattro.setCalStatus(3);
        quattro.setGFStatus(1);
        quattro.generateSubtitle();
        quattro.generateTypeString();
        quattro.setMapSearch("https://www.google.com/maps/search/?api=1&query=quattro+reading");
        quattro.setPhoneNum("01189483070");
        mLocations.add(quattro);

        RBLocation crownOnTheBridge = new RBLocation();
        crownOnTheBridge.setTitle("The Crown On The Bridge");
        crownOnTheBridge.setFoodType("Gastropub Grub");
        crownOnTheBridge.setArea("Caversham");
        crownOnTheBridge.setIsGastroPub(true);
        crownOnTheBridge.setVegStatus(2);
        crownOnTheBridge.setCalStatus(3);
        crownOnTheBridge.setGFStatus(1);
        crownOnTheBridge.generateSubtitle();
        crownOnTheBridge.generateTypeString();
        crownOnTheBridge.setMapSearch("https://www.google.com/maps/search/?api=1&query=crown+on+the+bridge+reading");
        crownOnTheBridge.setPhoneNum("01189471407");
        mLocations.add(crownOnTheBridge);

        RBLocation binaTandoori = new RBLocation();
        binaTandoori.setTitle("Bina Tandoori");
        binaTandoori.setFoodType("Indian/Nepalese");
        binaTandoori.setArea("Caversham");
        binaTandoori.setIsRestaurant(true);
        binaTandoori.setVegStatus(2);
        binaTandoori.setCalStatus(3);
        binaTandoori.setGFStatus(3);
        binaTandoori.generateSubtitle();
        binaTandoori.generateTypeString();
        binaTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=bina+tandoori+reading");
        binaTandoori.setPhoneNum("01189462115");
        mLocations.add(binaTandoori);

        RBLocation himalayaMomo = new RBLocation();
        himalayaMomo.setTitle("Himalaya Momo House");
        himalayaMomo.setFoodType("Indian/Nepalese");
        himalayaMomo.setArea("Caversham");
        himalayaMomo.setIsRestaurant(true);
        himalayaMomo.setVegStatus(2);
        himalayaMomo.setCalStatus(3);
        himalayaMomo.setGFStatus(2);
        himalayaMomo.generateSubtitle();
        himalayaMomo.generateTypeString();
        himalayaMomo.setMapSearch("https://www.google.com/maps/search/?api=1&query=himalaya+momo+reading");
        himalayaMomo.setPhoneNum("01189484818");
        mLocations.add(himalayaMomo);

        RBLocation asianSpice = new RBLocation();
        asianSpice.setTitle("Asian Spice");
        asianSpice.setFoodType("Indian/Nepalese");
        asianSpice.setArea("Tilehurst");
        asianSpice.setIsRestaurant(true);
        asianSpice.setVegStatus(2);
        asianSpice.setCalStatus(3);
        asianSpice.setGFStatus(3);
        asianSpice.generateSubtitle();
        asianSpice.generateTypeString();
        asianSpice.setMapSearch("https://www.google.com/maps/search/?api=1&query=asian+spice+tilehurst");
        asianSpice.setPhoneNum("01189455595");
        mLocations.add(asianSpice);

        RBLocation masala22 = new RBLocation();
        masala22.setTitle("Masala 22");
        masala22.setFoodType("Indian/Nepalese");
        masala22.setArea("Tilehurst");
        masala22.setIsRestaurant(true);
        masala22.setVegStatus(2);
        masala22.setCalStatus(3);
        masala22.setGFStatus(3);
        masala22.generateSubtitle();
        masala22.generateTypeString();
        masala22.setMapSearch("https://www.google.com/maps/search/?api=1&query=masala+22+tilehurst");
        masala22.setPhoneNum("01189672720");
        mLocations.add(masala22);

        RBLocation sunkoshiTandoori = new RBLocation();
        sunkoshiTandoori.setTitle("Sunkoshi Tandoori");
        sunkoshiTandoori.setFoodType("Indian/Nepalese");
        sunkoshiTandoori.setArea("Tilehurst");
        sunkoshiTandoori.setIsRestaurant(true);
        sunkoshiTandoori.setVegStatus(2);
        sunkoshiTandoori.setCalStatus(3);
        sunkoshiTandoori.setGFStatus(3);
        sunkoshiTandoori.generateSubtitle();
        sunkoshiTandoori.generateTypeString();
        sunkoshiTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=sunkoshi+tandoori+tilehurst");
        sunkoshiTandoori.setPhoneNum("01189425173");
        mLocations.add(sunkoshiTandoori);

        RBLocation zyka = new RBLocation();
        zyka.setTitle("Zyka");
        zyka.setFoodType("Indian/Nepalese");
        zyka.setArea("Tilehurst");
        zyka.setIsRestaurant(true);
        zyka.setVegStatus(3);
        zyka.setCalStatus(3);
        zyka.setGFStatus(3);
        zyka.generateSubtitle();
        zyka.generateTypeString();
        zyka.setMapSearch("https://www.google.com/maps/search/?api=1&query=zyka+tilehurst");
        zyka.setPhoneNum("01189427788");
        mLocations.add(zyka);

        RBLocation everestTandoori = new RBLocation();
        everestTandoori.setTitle("The Everest Tandoori");
        everestTandoori.setFoodType("Indian/Nepalese");
        everestTandoori.setArea("Tilehurst");
        everestTandoori.setIsRestaurant(true);
        everestTandoori.setVegStatus(2);
        everestTandoori.setCalStatus(3);
        everestTandoori.setGFStatus(3);
        everestTandoori.generateSubtitle();
        everestTandoori.generateTypeString();
        everestTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=everest+tandoori+tilehurst");
        everestTandoori.setPhoneNum("01189588853");
        mLocations.add(everestTandoori);

        RBLocation whiteHorse = new RBLocation();
        whiteHorse.setTitle("White Horse");
        whiteHorse.setFoodType("Gastropub Grub");
        whiteHorse.setArea("Emmer Green");
        whiteHorse.setIsGastroPub(true);
        whiteHorse.setVegStatus(2);
        whiteHorse.setCalStatus(3);
        whiteHorse.setGFStatus(2);
        whiteHorse.generateSubtitle();
        whiteHorse.generateTypeString();
        whiteHorse.setMapSearch("https://www.google.com/maps/search/?api=1&query=white+horse+reading");
        whiteHorse.setPhoneNum("01189473741");
        mLocations.add(whiteHorse);

        RBLocation villageTandoori = new RBLocation();
        villageTandoori.setTitle("Village Tandoori");
        villageTandoori.setFoodType("Indian/Nepalese");
        villageTandoori.setArea("Emmer Green");
        villageTandoori.setIsRestaurant(true);
        villageTandoori.setVegStatus(2);
        villageTandoori.setCalStatus(3);
        villageTandoori.setGFStatus(3);
        villageTandoori.generateSubtitle();
        villageTandoori.generateTypeString();
        villageTandoori.setMapSearch("https://www.google.com/maps/search/?api=1&query=village+tandoori+reading");
        villageTandoori.setPhoneNum("01189463939");
        mLocations.add(villageTandoori);

        RBLocation theGardnersArms = new RBLocation();
        theGardnersArms.setTitle("The Gardner's Arms");
        theGardnersArms.setFoodType("Gastropub Grub");
        theGardnersArms.setArea("Emmer Green");
        theGardnersArms.setIsGastroPub(true);
        theGardnersArms.setVegStatus(1);
        theGardnersArms.setCalStatus(2);
        theGardnersArms.setGFStatus(2);
        theGardnersArms.generateSubtitle();
        theGardnersArms.generateTypeString();
        theGardnersArms.setMapSearch("https://www.google.com/maps/search/?api=1&query=gardners+arms+reading");
        theGardnersArms.setPhoneNum("01189481507");
        mLocations.add(theGardnersArms);

    }

    public List<RBLocation> getLocations() {
        return mLocations;
    }

    public RBLocation getLocation(UUID id) {
        for (RBLocation location : mLocations) {
            if (location.getId().equals(id)) {
                return location;
            }
        }
        return null;
    }
}
